[package]
name = "sn_launch_tool"
version = "0.0.16"
description = "SAFE API"
authors = [ "Gabriel Viganotti <gabrielviganotti@gmail.com>" ]
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/sn_launch_tool.git"
edition = "2018"

[dependencies]
directories = "3.0.1"
env_logger = "~0.8.3"
log = "~0.4.14"
serde_json = "1.0.62"
structopt = "~0.3.21"
